#!/usr/bin/env python3
"""
daily-ai-news-wechat: Fetch and summarize daily AI news from WeChat public accounts, then push to user.
"""

import os
import sys
import json
from datetime import datetime

# Add the skill directory to path
skill_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(skill_dir, "scripts"))

from wechat_utils import WeChatClient

def load_accounts():
    """Load list of public accounts to follow"""
    accounts_path = os.path.join(skill_dir, "references", "accounts.md")
    accounts = []
    with open(accounts_path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line.startswith("- `"):
                # Extract account name from format: - `Name` : Description
                name_part = line.split("`")[1]
                accounts.append(name_part)
    return accounts

def load_summary_prompt():
    """Load summary prompt template"""
    prompt_path = os.path.join(skill_dir, "references", "prompt.md")
    with open(prompt_path, "r", encoding="utf-8") as f:
        return f.read()

def fetch_latest_articles(accounts):
    """
    Fetch latest articles from configured WeChat public accounts.
    In a real implementation, this would connect to WeChat API / RSS feed.
    For now, this returns placeholder content that demonstrates the structure.
    """
    today = datetime.now().strftime("%Y-%m-%d")
    # TODO: Implement actual fetching based on your WeChat access method
    # This is a placeholder that you can replace with actual API calls
    articles = []
    
    # Example placeholder article structure
    # articles.append({
    #     "title": "Example Article Title",
    #     "url": "https://mp.weixin.qq.com/s/example",
    #     "author": "Author Name",
    #     "content": "Full article content here...",
    #     "account": "Account Name",
    #     "publish_time": today
    # })
    
    return articles

def summarize_article(article, prompt_template):
    """
    Summarize article using LLM.
    This uses OpenClaw's built-in summarization capability.
    """
    # In actual implementation, you would call the LLM here
    # For now, we create the structure that will be used
    prompt = prompt_template.replace("{{ARTICLE_CONTENT}}", article["content"])
    # The actual summarization happens in the agent turn
    return prompt

def format_digest(summarized_articles):
    """Format the daily digest for WeChat sending"""
    today = datetime.now().strftime("%Y年%m月%d日")
    digest = f"📰 每日AI早报 - {today}\n\n"
    
    if not summarized_articles:
        digest += "今天没有获取到新的相关文章。"
        return digest
    
    for i, article in enumerate(summarized_articles, 1):
        digest += f"{i}. **{article['title']}**\n"
        digest += f"🔗 {article['url']}\n"
        digest += f"📝 {article['summary']}\n\n"
    
    digest = digest.strip()
    return digest

def main():
    print("Starting daily AI news fetch...")
    
    # Load configuration
    accounts = load_accounts()
    prompt_template = load_summary_prompt()
    
    if not accounts:
        print("No accounts configured. Please add accounts to references/accounts.md")
        return 1
    
    print(f"Loaded {len(accounts)} accounts to check")
    
    # Fetch articles
    articles = fetch_latest_articles(accounts)
    print(f"Fetched {len(articles)} new articles")
    
    if not articles:
        print("No new articles found today")
        # Still send empty digest to confirm it's running
        digest = format_digest([])
    else:
        # Each article needs to be summarized by the LLM
        # This part is handled by the agent during the cron run
        summarized_articles = []
        for article in articles:
            prompt = summarize_article(article, prompt_template)
            # Summary would be generated here
            summarized_articles.append({
                "title": article["title"],
                "url": article["url"],
                "summary": "[Summary to be generated by LLM]"
            })
        digest = format_digest(summarized_articles)
    
    # Send to WeChat
    wechat = WeChatClient()
    success = wechat.send_message(digest)
    
    if success:
        print("Daily digest sent successfully to WeChat")
        return 0
    else:
        print("Failed to send message to WeChat")
        return 1

if __name__ == "__main__":
    sys.exit(main())
